### PR TITLE
Remove dead Places protocol handler

### LINKED ISSUE #1665: Places protocol handler doesn't do anything useful (code cleanup)
Places protocol handler doesn't do anything useful and is just code bloat, so it's safe to remove it.

See: https://bugzilla.mozilla.org/show_bug.cgi?id=737046.

### PR DESCRIPTION
**Pull request by JustOff**
Based on https://bugzilla.mozilla.org/show_bug.cgi?id=737046.

Resolves #1665.

### CODE REVIEW

**Comment by mattatobin** [comment]
Isn't the places protocol used by extensions?

**Comment by JustOff** [comment]
I doubt that this is possible, because the implementation has never been completed, see: [Bug 737046 - RESOLVED WONTFIX](https://bugzilla.mozilla.org/show_bug.cgi?id=737046).

**Comment by mattatobin** [comment]
Hmm.. let me get back to you on that.. Albeit.. the patch here on Tycho is moot.. @wolfbeast can decide if it lands here.. As for UXP.. Let me get back to you on that.

**Comment by wolfbeast** [comment]
Any decision will have to wait until GitHub is fixed.

**Comment by wolfbeast** [comment]
Incomplete code cleanup - sure either way; since the work is already done, may as well merge it in.

**Comment by JustOff** [comment]
> Incomplete code cleanup

You mean b2g staff?

**Comment by wolfbeast** [comment]
No, I mean it's cleanup of incomplete code.

> the implementation has never been completed, see: Bug 737046 - RESOLVED WONTFIX.

**Pull request merged**
