### PR TITLE
Windows 10 theme changes

### PR DESCRIPTION
**Pull request by Lootyhoof**
In an effort to make the Windows 10 styling look more system-native, the following changes were made:

- Window title on dark windows frames is now not used in lwtheme mode. It was ignoring the styles the lwthemes wanted.
- Altered the close button animation. The most noticeable change here will be the opacity change when clicked - this is to mirror behavior in Windows 10.
- Bright caption buttons (for dark window frames) had the exact opposite issue of the window title above: it was working for lwthemes, but not inactive windows. I also lowered the brightness slightly to match the style used in the system.

### CODE REVIEW

**Comment by wolfbeast** [comment]
Native windows 10 has a brief transition on hover. This is why I made a transparent element as a click target with opacity change for hover with a short transition period to mirror native behavior. You're now doing away with all that?...

**Comment by Lootyhoof** [comment]
In the current implementation, the opacity set to 0 makes it misbehave with lwthemes.

Caption buttons

The implementation in this PR retains the desired animation, while requiring less styles to do so.

With regards to things not looking right in certain configurations, this was bound to happen regardless of whether the background turns transparent on click anyway. If there's a misalignment, it'll be quite obvious with the other caption buttons too.

Misalignment

**Comment by wolfbeast** [comment]
What I eant with misalignment is the fact tha the X is actually drawn with our SVG any background transparency if the system "X" is misaligned will cause blurring or ghosting.

Also, previously, I'm quite sure the LWT remained untouched; i guess with the compacting of style rules something specific got dropped or overridden in previous patches then 

I'll merge this in and have another look myself

**Comment by wolfbeast** [comment]
Your PR doesn't fix the LWT issue.
Also, the close button lost its fade like I said; that's not good. it also flickers because of the on-the-fly loading of an image (which is also more expensive to do than just opacity compositor changes).

**Comment by wolfbeast** [comment]
I've compared the close button and it indeed goes transparent now (didn't do so in previous versions of Win10, I think) so your transparency is OK. I just hope it won't misalign on user's systems.

**Pull request merged**
