### PR TITLE
show list of translators in the language pack detail

### PR DESCRIPTION
**Pull request by JustOff**
palemoon_2016-12-08_21-05-36

https://forum.palemoon.org/viewtopic.php?p=99608#p99608

### CODE REVIEW

**Comment by JustOff** [comment]
@KNTRO Here is what I [meant](https://forum.palemoon.org/viewtopic.php?p=99619#p99619)

**Comment by KNTRO** [comment]
@JustOff Good job, JustOff! That's exactly how I imagined it! :+1:

**Comment by wolfbeast** [comment]
Absolutely great enhancement and giving credit where it's definitely due! Always been in the back of my mind to do this "some time" but never got around to it.

**Comment by KNTRO** [comment]
Just a little suggestion: could names/usernames be sorted alphabetically, despite its letter cases?

**Comment by JustOff** [comment]
@KNTRO I'm not sure that it would be fair. At least I'm going to put Pale Moon translators before Firefox ones. And in case of many translators range them according their contributions. But you can always ask to do otherwise in particular case.

**Comment by KNTRO** [comment]
@JustOff Understood. It is not a big deal, no problem. I just thought of this after the [about:credits](https://www.mozilla.org/credits/) format, where people are sorted alphabetically, no matter who is who. But again, it's not something that important after all, that's why I said _just a little suggestion_. :wink:

**Comment by janekptacijarabaci** [comment]
@JustOff 
I have a suggestion for the Czech translation:
```
<em:translator>Pavel Cvrček</em:translator>
<em:translator>Pavel Franc</em:translator>
<em:translator>Jan Havlena</em:translator>
<em:translator>Filip Hruška</em:translator>
<em:translator>janekptacijarabaci</em:translator>
<em:translator>Michal Kec</em:translator>
<em:translator>ragulin</em:translator>
<em:translator>Sam</em:translator>
<em:translator>Sob__</em:translator>
<em:translator>Michal Stanke</em:translator>
<em:translator>Michal Vašíček</em:translator>
<em:translator>Tomáš Zelina</em:translator>
```
I consulted with Michal Stanke (Lead of Czech Mozilla.cz l10n community).

@MikkCZ
It is in alphabetical order.

**Comment by JustOff** [comment]
@janekptacijarabaci 
Ok, so will be in the next build and further.

**Pull request merged**
