### PR TITLE
Pale Moon 26 - patch for the default Windows theme

### PR DESCRIPTION
**Pull request by Antonius32**
This pull request introduces the following changes:

- Make sure that when the tabs are *not* on top, the Navigation toolbar buttons are vertically centered between the Bookmarks toolbar / the tabs on one side, and the AppMenu button (or the title bar) on the other
- Set margin on the Tab bar as a whole, instead of on the individual items it holds
- Make the tab corners more distinct/clean-cut
- Add a small visual gap between the tabs and the Menu bar / the top edge of the screen
- Make sure scrolling down to the last tab with the mousewheel disables the tab scrollbox's scroll-down arrow (for reference, see [this] (http://forum.palemoon.org/viewtopic.php?f=45&t=10828#p75823) post on the forum)

Additional change:

- Make sure that on Aero-enabled systems, the Tab bar is always transparent in full-screen mode

This is a revision of / follow-up to PRs #309, #310 and #313, which were reverted by commit f7c143e.

### CODE REVIEW

**Comment by Antonius32** [comment]
@wolfbeast Tested and confirmed working on Windows 7. Should work on Windows 8 and 10 as well.

**Comment by wolfbeast** [comment]
I'll have a look at this tomorrow with a build and a test run on XP, 8 and 10

**Comment by Antonius32** [comment]
All right, I hope it all works as intended now!

**Comment by wolfbeast** [comment]
Getting there. Tested some on Win 7 and Win 8 until now while having a moment.

A few issues:

- All versions, fullscreen mode, tabs on bottom: the tab bar background is not glass/toolbar when the bookmarks toolbar is enabled (but not visible in fullscreen mode). I'm not sure if this is actually a different bug (might be) but you may be able to tweak it while you're in there?
- Win8 (and probably win 10) maximized+fullscreen, tabs on top: Tabs are rounded. Also, this seems to be a larger rounding than normal? Please keep things consistent. Define rounding once for each OS and don't override it later, to prevent this.

Borders seem to be drawn correctly :+1:

**Comment by wolfbeast** [comment]
well that was based on the main commits, not the additions added more recently...

**Comment by Antonius32** [comment]
I've just made a last-minute adjustment to make sure the patch works as intended for Windows 8.

**Comment by wolfbeast** [comment]
Github was being odd - it showed 2 more entries with 2 files changed each, 22 hours ago...

**Comment by Antonius32** [comment]
Well, I rebased to change some of the comments in the mean time, maybe that's why. I haven't changed any actual code until just now, though.

**Comment by Antonius32** [comment]
Anyway, I think the rounding of the tabs should be OK now.

I'm not sure if the the Tab bar background in full-screen mode is a bug; I think that with the darker background, it would be hard to distinguish the All Tabs button. But for consistency, maybe the tabs should have the transparent border here as well. What do you think?

**Comment by Antonius32** [comment]
Commit 3531cef makes sure that on Aero-enabled systems, the Tab bar is always transparent in full-screen mode.

As far as I'm concerned, the patch is good to go now.

**Comment by Antonius32** [comment]
After a final revision of the first commit, the patch should be good to go now.

**Pull request merged**
