### PR TITLE
Infer from each toolbar's text color whether we should use inverted icons

### PR DESCRIPTION
**Pull request by Lootyhoof**
This commit adds the `brighttext` attribute to `toolbar` when the text colour is bright (such as when a lwtheme is applied). As such, this is a way to detect dark themes cross-platform, as well as reducing the amount of styles needed to style for lwthemes and Windows-specific styling. 

Addendum to #219.

### CODE REVIEW

**Comment by wolfbeast** [comment]
Looks good, but one question: You're calculating the luminance independently of what was recently added for the dark window frame - does the test have the same flip point?

**Comment by Lootyhoof** [comment]
As far as I'm aware, this algorithm is pulled directly from `LightweightThemeConsumer.jsm`, so anything that applies there will also apply here.

**Comment by wolfbeast** [comment]
What threw me off was that you said it was an addendum to #219 -- but actually it isn't, since this just looks at the existing text color from LWTs...

Also, I don't see how this reduces the amount of styles needed -- it just exchanges `:-moz-lwtheme-brighttext` suffixes with a `toolbar` element preselector...? if anything it makes it more ambiguous what people should use...?

Or stated another way: why do we actually need this?

**Comment by Lootyhoof** [comment]
>What threw me off was that you said it was an addendum to #219 -- but actually it isn't, since this just looks at the existing text color from LWTs...

Please understand that while this uses a similar algorithm to lwthemes, it is NOT the same thing, primarily due to the method of execution. While the current algorithm decides whether we are using `-moz-lwtheme-brighttext` when a lwtheme is applied, this will instead check if the **system theme itself** is dark, by checking the text colour **at all times**. This is different to (and complements nicely) `darkwindowframe`, as that is Windows specific, and still useful for titlebar elements that don't exist within a `toolbar`.

>Also, I don't see how this reduces the amount of styles needed

This was my bad, sorry about that - I did make some large changes but changed them at the last minute as they were a little too heavy-handed.

>if anything it makes it more ambiguous what people should use...?

Think of it this way:

When styling **chrome**, use `-moz-lwtheme`, as we surely don't need different toolbar stylings for a dark theme but may be desirable for a dark lwtheme.
When styling **icons**, use `toolbar[brighttext]`. If a dark theme is present we might lose legibility of the icons, so we can replace them with inverted (or otherwise brighter) icons in this instance. This also includes dark lwthemes.

**Comment by wolfbeast** [comment]
I think I get it, but won't this cause issues with LWTs then? I mean, you'd be looking at 2 different ways to determine what icons should be used. This means that this should *only* be used is you're not using a lightweight theme, i.e.: when the default theme is in use, otherwise you can get inverted icons on a light LWT just because the chose system theme is dark, and the other way around; it would override LWT icon styling...

**Comment by Lootyhoof** [comment]
This applies to **both** dark system themes and dark lwthemes. The distinction is that, while `toolbar[brighttext]` can work for both, `-moz-lwtheme-brighttext` only works for dark lwthemes. Both of these have their uses.

Note that when a **light** lwtheme is applied, `toolbar` doesn't report as having `brighttext`, so this is a non-issue. It only reports `brighttext` when the text itself on the toolbar in question is bright.

**Comment by wolfbeast** [comment]
Oh, right, I missed the lwt text observer that was added. My bad. :)

**Pull request merged**
