### PR TITLE
Make tail dispatching automatic and happen on the main thread

### PR DESCRIPTION
**Pull request by trav90**
Just what it says in the tin. Only other changes are adjusting a few assertions and updating a couple tests. This should be the final big update to AbstractThread and TaskDispatcher, so this is one big hurdle behind us on the road to stabilizing our media code.

Tested on YouTube HD & Twitch and seems to be working as intended. Still adding the verification needed label since this is a substantive change (needs testing on Windows, obviously).

### CODE REVIEW

**Comment by JustOff** [comment]
Win7: build is ok, youtube, [cnn](http://edition.cnn.com/videos) & [reuters](http://feeds.reuters.com/reuters/USVideoTopNews) play fine, twitch & vimeo - only when mse disabled.

**Comment by trav90** [comment]
Twitch only plays with MSE disabled? Is that only after this PR or also prior? (I have MSE + MP4 enabled and Twitch plays fine).

**Comment by JustOff** [comment]
There was something strange with twitch and my profile, now after cookies cleanup it works fine with mse enabled too.

**Comment by trav90** [comment]
Great, thanks for confirming!

**Comment by wolfbeast** [comment]
So that just leaves Vimeo still being a bad apple for MSE/MP4 for us then?

**Comment by JustOff** [comment]
I also have problem with soundcloud and background playback when mse enabled and someone on forum complained about weather.com.

**Comment by trav90** [comment]
@JustOff does the same workaround for Vimeo (setting media.mediasource.format-reader.mp4 to false) work for soundcloud?

**Comment by mattatobin** [comment]
Cannot verify issues with SoundCloud.

**Comment by JustOff** [comment]
I had observed noticeable distortions after a while when playing soundcloud in background tab. That was in 27.1.0 or 27.1.1 and I've disabled mse for it since then. I'll check this once again with 27.2 and update.

**Comment by mattatobin** [comment]
I constantly listen to soundcloud in the background for hours a day most days and have not observed any issues. May want to check your system because I doubt this is something to do with Pale Moon code. Remember, mpeg codecs get offloaded to Windows Media Foundation at the end of their trip..

**Pull request merged**
