### PR TITLE
Silence compiler warnings in JXR decoder

### PR DESCRIPTION
**Pull request by rhinoduck**
As discussed in #105.

I didn't compile with GCC so maybe @trav90 will want to confirm they are all gone first (or maybe it just isn't worth a separate compile).

### CODE REVIEW

**Comment by trav90** [comment]
I'll kick off a build now.

**Comment by trav90** [comment]
Looks good here! Only 2 warnings left:

https://gist.github.com/trav90/93c35e099b4921ee8628bf8724604d86

Thanks!

**Comment by rhinoduck** [comment]
Agh, silly me. Copied the wrong names. Pushed a fixup commit, that should do it.

**Comment by rhinoduck** [comment]
Thanks for the feedback, I'll be going to bed now. I don't know what GitHub allows while rebasing in pull requests, maybe you can squash the fixup commit there. If not, but it allows you to force-push into this branch, you can do the squashing locally as `git rebase -i --autosquash HEAD~3` (an editor will open; just save and close) and then force-pushing it. If neither is possible, I'll do it when I wake up; if everything is alright.

**Comment by trav90** [comment]
Perfect! It now compiles without any warnings at all. Thanks!

**Comment by rhinoduck** [comment]
Squashed the fixup commit, and I think we're ready here. @wolfbeast

**Comment by wolfbeast** [comment]
Thanks for chasing these down :)

**Pull request merged**
