### PR TITLE
Downloads - It can't delete from history - using the context menu: "Remove From History"

### PR DESCRIPTION
**Pull request by janekptacijarabaci**
Ad #630 

See:
https://bugzilla.mozilla.org/show_bug.cgi?id=1115983 (partially)

---

You add the label `Verification Needed`, please.
Patches must be tested (with as many "variables" as possible).

(maybe also `Uplift Wanted`?)

---

I've created the new build (x32, Windows) and tested.

### CODE REVIEW

**Comment by wolfbeast** [comment]
Too late for an uplift; this isn't a blocker.

**Comment by wolfbeast** [comment]
Can someone verify this fix on trunk, please?

**Comment by wolfbeast** [comment]
Just verified myself, actually. removing the verification needed label.

**Comment by janekptacijarabaci** [comment]
@wolfbeast 
Ad https://github.com/MoonchildProductions/Pale-Moon/issues/1368

Is it possible to uplift to version 27.5.1?

**Comment by wolfbeast** [comment]
What does this have to do with #1368?

**Comment by janekptacijarabaci** [comment]
There will be a new minor version (maybe), nothing more.

**Comment by wolfbeast** [comment]
I'm only uplifting critically important things past initial release of a new major. Otherwise it's going to get messy keeping things organized and mistakes will be made.

**Pull request merged**
