### PR TITLE
Add -moz-os-version support

### PR DESCRIPTION
**Pull request by trav90**
Should resolve issue #120.

Possible followup bug: [1169981] (https://bugzilla.mozilla.org/show_bug.cgi?id=1169981)

### CODE REVIEW

**Comment by wolfbeast** [comment]
Looks like the follow-up bug will be needed because of Win 10 MQ support

**Comment by trav90** [comment]
I'll try to get another PR for that submitted this weekend.

**Comment by trav90** [comment]
The above mentioned bug [1169981] (https://bugzilla.mozilla.org/show_bug.cgi?id=1169981) appears to be dependent on the changes made in the first patch of [1150006] (https://bugzilla.mozilla.org/show_bug.cgi?id=1150006).

**Comment by wolfbeast** [comment]
I don't want bug 1150006 because it can and will break existing themes. Maybe you can discuss this with Ryan (Lootyhoof) to see that the impact of it would be, but it'd likely be better to just rewrite the 1169981 patch to apply to our current setup. If you prefer, I can look at that in a follow-up.

**Comment by wolfbeast** [comment]
Actually... did you look at the patch for ESR? the main patch is for trunk but the ESR patch doesn't have the -aero yanked.

**Comment by trav90** [comment]
Yes, I was looking at the ESR patch last night. I posted the comment mostly for my reference for when I work on this the next few days. :)

**Comment by trav90** [comment]
```
"it'd likely be better to just rewrite the 1169981 patch to apply to our current setup."
```

I've gone over the patch(es) on BMO several times, but I'm not sure how to rewrite the patch correctly?

**Comment by wolfbeast** [comment]
The ESR one might apply better, not needing a rewrite.

**Comment by wolfbeast** [comment]
Build failure with this PR: 

 5:39.74 e:/mozdev/PaleMoon/widget/windows/nsLookAndFeel.cpp(402) : error C2039: 'WIN10_VERSION' : i
s not a member of 'mozilla::widget::WinUtils'
 5:39.74
 5:39.74         e:\mozdev\palemoon\widget\windows\WinUtils.h(41) : see declaration of 'mozilla::wid
get::WinUtils'
 5:39.74
 5:39.74 e:/mozdev/PaleMoon/widget/windows/nsLookAndFeel.cpp(402) : error C2065: 'WIN10_VERSION' : u
ndeclared identifier
 5:39.74
 5:39.74 e:/mozdev/PaleMoon/widget/windows/nsLookAndFeel.cpp(402) : error C2051: case expression not
 constant

**Comment by wolfbeast** [comment]
Looks like it's just missing 0xa00 for Windows 10. Easy enough to add.
We'll have to see if it actually picks up the correct version with getVersionEx() because Microsoft has been deprecating it in Win 8.1

**Comment by wolfbeast** [comment]
Commit 724c9ea should fix this

**Comment by trav90** [comment]
Thanks.

**Comment by trav90** [comment]
```
"The ESR one might apply better, not needing a rewrite."
```

The patch as-is on BMO puts it in the middle of a bunch of non-existent code in Pale Moon. I'm not sure where the correct location in the file to apply the patch.

**Comment by Lootyhoof** [comment]
A bit late to be commenting on this, but 1150006 doesn't apply to us anyway; -aero suffixes were added in Fx40 with [70613] (https://bugzilla.mozilla.org/show_bug.cgi?id=706103).

**Comment by wolfbeast** [comment]
We'll have to look at this a different way. Since we don't have the refactored -aero things, we simply need to make use of our new os switches and use those to make the win8 and win10 stuff flat and square.

**Pull request merged**
