### PR TITLE
Added classic status bar

### PR DESCRIPTION
**Pull request by BitVapor**
I'm starting off simple with my first pull request.  One tweak, only affects OS X builds.
screen shot 2015-04-03 at 9 31 25 pm

### CODE REVIEW

**Comment by wolfbeast** [comment]
Yup, looks good.

**Comment by wolfbeast** [comment]
Tobin sent me a note about this:
> packager.mk for macos needs to be ifdef'd to MOZ_PHOENIX for statusbar inclusion
> in case someone builds something else than Pale Moon for mac..
> like FossaMail
> or xulrunner
So it needs the original line in there still, as an #else and the new in an #ifdef MOZ_PHOENIX block. See the other packager scripts for hints.

**Comment by BitVapor** [comment]
Groovy.  Will investigate further.

**Comment by mattatobin** [comment]
Fixed in 04b5f8c27c1e4972c87b5e9299a05593e2824e62

**Pull request merged**
