### PR TITLE
Add UA overridde for Dropbox

### PR DESCRIPTION
**Pull request by adeshkp**
Native UA mode added a while back doesn't work anymore

### CODE REVIEW

**Comment by mattatobin** [comment]
You're kidding right? IE? Can you not find something closer to a Mozilla UA?

**Comment by Sa-Ja-Di** [comment]
what works:

Mozilla/5.0 (Windows NT 6.3; Win64; x64; rv:10.0) Gecko/20100101 Firefox/10.0


until

Mozilla/5.0 (Windows NT 6.3; Win64; x64; rv:50.0) Gecko/20100101 Firefox/50.0

If taking a user agent above 52, Dropbox page is only partly usable. IE user agent looks like the more stable choice imho ;)

**Comment by adeshkp** [comment]
@mattatobin 
Only after Moonchild.
https://forum.palemoon.org/viewtopic.php?f=19&t=18235&p=136533#p134028

**Comment by wolfbeast** [comment]
Merging this in. We can change it again if they break it again.

**Comment by sergeevabc** [comment]
Thank you.

**Pull request merged**
