### PR TITLE
Make Ciphersuite and TLS Protocol visible

### PR DESCRIPTION
**Pull request by trav90**
User request: https://forum.palemoon.org/viewtopic.php?f=13&t=7843

Bug numbers:  [886752] (https://bugzilla.mozilla.org/show_bug.cgi?id=886752) & [947149] (https://bugzilla.mozilla.org/show_bug.cgi?id=947149)

### CODE REVIEW

**Comment by trav90** [comment]
Sorry the pull request is kind of a mess. End result should be clean though.

**Comment by wolfbeast** [comment]
Please don't logroll unrelated fixes into a single pull request :(
I'll separate them out from the patch diff.

In addition, I think this builds on top of bug 820887 -- did you build and test it? I've just implemented the NSS callback cleanup from that bug#, myself. That in turn needs more frontend work to convert the cryptic cipher string to something a bit more friendly (which is what i wanted to do, to begin with). A ping before implementing would have been useful in this case.

**Comment by wolfbeast** [comment]
Oh, I see.. you reverted the stuff back out, my bad.
Still would like to know the end result if it builds without 820887 and what the output is - might actually simplify things.

**Comment by trav90** [comment]
> Please don't logroll unrelated fixes into a single pull request :(

Yeah, that was my bad. I created a new branch in order to keep them separate, except that without even thinking, I created it from master which already had the previous commits. Sorry about that!

I had started the build process with the patch applied right before I went to bed, so I hadn't tested it yet. The build did end up failing:

```
/home/palemoon/PaleMoon/pmsrc/security/manager/ssl/src/nsNSSCallbacks.cpp: In function ‘void HandshakeCallback(PRFileDesc*, void*)’:
/home/palemoon/PaleMoon/pmsrc/security/manager/ssl/src/nsNSSCallbacks.cpp:952:57: error: ‘class nsSSLStatus’ has no member named ‘mKeyLength’
/home/palemoon/PaleMoon/pmsrc/security/manager/ssl/src/nsNSSCallbacks.cpp:953:27: error: ‘channelInfo’ was not declared in this scope
make[7]: *** [nsNSSCallbacks.o] Error 1
make[7]: *** Waiting for unfinished jobs....
/home/palemoon/PaleMoon/pmsrc/security/manager/ssl/src/nsNSSCertificate.cpp: In member function ‘virtual nsresult nsNSSCertificate::GetChain(nsIArray**)’:
/home/palemoon/PaleMoon/pmsrc/security/manager/ssl/src/nsNSSCertificate.cpp:831:13: warning: variable ‘srv’ set but not used [-Wunused-but-set-variable]
make[7]: Leaving directory `/home/palemoon/PaleMoon/pmbuild/security/manager/ssl/src'
make[6]: *** [libs] Error 2
make[6]: Leaving directory `/home/palemoon/PaleMoon/pmbuild/security/manager/ssl'
make[5]: *** [libs] Error 2
make[5]: Leaving directory `/home/palemoon/PaleMoon/pmbuild/security/manager'
make[4]: *** [libs_tier_platform] Error 2
make[4]: Leaving directory `/home/palemoon/PaleMoon/pmbuild'
make[3]: *** [tier_platform] Error 2
make[3]: Leaving directory `/home/palemoon/PaleMoon/pmbuild'
make[2]: *** [default] Error 2
make[2]: Leaving directory `/home/palemoon/PaleMoon/pmbuild'
make[1]: *** [realbuild] Error 2
make[1]: Leaving directory `/home/palemoon/PaleMoon/pmsrc'
make: *** [build] Error 2
```
I'll be more mindful of doing testing before submitting requests in the future (as well as sending you a ping if I'm thinking a submitting a patch).

That said, it looks like to me (I could be wrong), it is failing on a line that has been removed from the latest commit. I'll apply your patch from bug 820887 and attempt another build. I'll report back.

**Comment by trav90** [comment]
Build still fails even after adding the latest commit:

```
/home/palemoon/PaleMoon/pmsrc/security/manager/ssl/src/nsNSSCallbacks.cpp: In function ‘void HandshakeCallback(PRFileDesc*, void*)’:
/home/palemoon/PaleMoon/pmsrc/security/manager/ssl/src/nsNSSCallbacks.cpp:975:13: error: ‘class nsSSLStatus’ has no member named ‘mHaveKeyLengthAndCipher’
/home/palemoon/PaleMoon/pmsrc/security/manager/ssl/src/nsNSSCallbacks.cpp:976:13: error: ‘class nsSSLStatus’ has no member named ‘mKeyLength’
/home/palemoon/PaleMoon/pmsrc/security/manager/ssl/src/nsNSSCallbacks.cpp:977:13: error: ‘class nsSSLStatus’ has no member named ‘mSecretKeyLength’
/home/palemoon/PaleMoon/pmsrc/security/manager/ssl/src/nsNSSCallbacks.cpp:979:13: error: ‘class nsSSLStatus’ has no member named ‘mCipherName’
make[7]: *** [nsNSSCallbacks.o] Error 1
make[7]: *** Waiting for unfinished jobs....
/home/palemoon/PaleMoon/pmsrc/security/manager/ssl/src/nsNSSIOLayer.cpp: In member function ‘void nsNSSSocketInfo::GetPreviousCert(nsIX509Cert**)’:
/home/palemoon/PaleMoon/pmsrc/security/manager/ssl/src/nsNSSIOLayer.cpp:427:12: warning: unused variable ‘rv’ [-Wunused-variable]
make[7]: Leaving directory `/home/palemoon/PaleMoon/pmbuild/security/manager/ssl/src'
make[6]: *** [libs] Error 2
make[6]: Leaving directory `/home/palemoon/PaleMoon/pmbuild/security/manager/ssl'
make[5]: *** [libs] Error 2
make[5]: Leaving directory `/home/palemoon/PaleMoon/pmbuild/security/manager'
make[4]: *** [libs_tier_platform] Error 2
make[4]: Leaving directory `/home/palemoon/PaleMoon/pmbuild'
make[3]: *** [tier_platform] Error 2
make[3]: Leaving directory `/home/palemoon/PaleMoon/pmbuild'
make[2]: *** [default] Error 2
make[2]: Leaving directory `/home/palemoon/PaleMoon/pmbuild'
make[1]: *** [realbuild] Error 2
make[1]: Leaving directory `/home/palemoon/PaleMoon/pmsrc'
make: *** [build] Error 2
```

**Comment by wolfbeast** [comment]
I think it's likely a case of running into some refactoring that was done (or rather arbitrarily renaming).

Also, your second error makes no real sense since you've removed those lines in nsNSSCallback.cpp that wants to assign these values. have you tried clobbering?

**Comment by trav90** [comment]
I didn't realize until I was applying the patch, but those lines in nsNSSCallback.cpp are are in different lines now; they are actually still there.

I'm trying clobbering now. I'll report back.

**Comment by wolfbeast** [comment]
Did you use the actual hg commits or the patches in the bug? Often, the hg commits have last-minute changes to them that are not posted in the patches (bad practice, I know, but so it goes)

**Comment by wolfbeast** [comment]
I think your patch has an issue.

    - status->mHaveKeyLengthAndCipher = true;
    - status->mKeyLength = keyLength;
    - status->mSecretKeyLength = encryptBits;
    - status->mCipherName.Assign(cipherName);
    + status->mHaveCipherSuiteAndProtocol = true; status->mKeyLength = keyLength;
    + status->mCipherSuite = channelInfo.cipherSuite;
    + status->mProtocolVersion = channelInfo.protocolVersion & 0xFF;

But you also have:

     nsSSLStatus::nsSSLStatus()
    -: mKeyLength(0), mSecretKeyLength(0)
    +: mCipherSuite(0)
    +, mProtocolVersion(0)
    , mIsDomainMismatch(false)
    , mIsNotValidAtThisTime(false)
    , mIsUntrusted(false)
    -, mHaveKeyLengthAndCipher(false)
    +, mHaveCipherSuiteAndProtocol(false)
    , mHaveCertErrorBits(false)
Your build error complains about mHaveKeyLengthAndCipher. So something didn't apply properly, since it was removed.
mKeyLength was also removed from nsSSLStatus in your patch... so please double-check if those changes applied.

**Comment by trav90** [comment]
I used the patches in the bug; I wasn't aware that the hg commits could have changes in them (the first commit adds a line included in the hg patch that wasn't in the bug patch).
You're right, instead of replacing the value of a line, I added the new value in front of it (second commit fixes that).

Still have a build error, but making progress I think (note that this is without the bug 820887 patch):

```
/home/palemoon/PaleMoon/pmsrc/security/manager/ssl/src/nsNSSCallbacks.cpp: In function ‘void HandshakeCallback(PRFileDesc*, void*)’:
/home/palemoon/PaleMoon/pmsrc/security/manager/ssl/src/nsNSSCallbacks.cpp:953:27: error: ‘channelInfo’ was not declared in this scope
make[7]: *** [nsNSSCallbacks.o] Error 1
make[7]: *** Waiting for unfinished jobs....
/home/palemoon/PaleMoon/pmsrc/security/manager/ssl/src/nsNSSCertificate.cpp: In member function ‘virtual nsresult nsNSSCertificate::GetChain(nsIArray**)’:
/home/palemoon/PaleMoon/pmsrc/security/manager/ssl/src/nsNSSCertificate.cpp:831:13: warning: variable ‘srv’ set but not used [-Wunused-but-set-variable]
make[7]: Leaving directory `/home/palemoon/PaleMoon/pmbuild/security/manager/ssl/src'
make[6]: *** [libs] Error 2
make[6]: Leaving directory `/home/palemoon/PaleMoon/pmbuild/security/manager/ssl'
make[5]: *** [libs] Error 2
make[5]: Leaving directory `/home/palemoon/PaleMoon/pmbuild/security/manager'
make[4]: *** [libs_tier_platform] Error 2
make[4]: Leaving directory `/home/palemoon/PaleMoon/pmbuild'
make[3]: *** [tier_platform] Error 2
make[3]: Leaving directory `/home/palemoon/PaleMoon/pmbuild'
make[2]: *** [default] Error 2
make[2]: Leaving directory `/home/palemoon/PaleMoon/pmbuild'
make[1]: *** [realbuild] Error 2
make[1]: Leaving directory `/home/palemoon/PaleMoon/pmsrc'
make: *** [build] Error 2
```

I'm going to apply 820887 and try building again.

**Comment by wolfbeast** [comment]
You may be better off rebasing your work (maybe start fresh) on the current master, which has a working build state with the NSS callback optimization implemented already.

**Comment by wolfbeast** [comment]
Also, the main bug for improving sec info also has a much earlier patch attached to it (before it was put on ice because people were happy wit the raw cipher suite string). I haven't looked at that code but if it includes the protocol as well, then it may be better and easier to work from that 2013 patch than trying to deal with refactored BS

**Comment by wolfbeast** [comment]
I looked at the patch some more - you should make this a lot simpler and not pick up any of the refactoring/renaming that's included. That's just nonsense cruft that shouldn't even be IN this bugpatch.

Just ass a protocol to the info request and set it in the resulting struct to be pulled out to the frontend via the nsISSLStatus interface. That should be fairly straightforward. I fyou're not comfortable with implementing that, then I can do it instead. I'd rather not lose the record info with individual key lengths that is very useful to have, in favor of a cryptic string.

**Comment by trav90** [comment]
I was thinking the same thing, about starting fresh. I'll also take a look at the 2013 patch you mentioned.

> Just add a protocol to the info request and set it in the resulting struct to be pulled out to the frontend via the nsISSLStatus interface. That should be fairly straightforward. If you're not comfortable with implementing that, then I can do it instead.

I'd love to try, but I'm not exactly sure what I need to do to accomplish this? (sorrry for my ignorance)

**Comment by wolfbeast** [comment]
OK, well, just try to implement the current bugs listed on top of the updated master. It is actually not a disaster because key sizes may actually be confusing (RSA keys are much larger than ECDHE ones with the same cryptographic strength) and I can just build a simple suite string parser on top of that in the front-end to make it more readable than the raw string. We can evaluate later what would be more useful.

**Comment by trav90** [comment]
For some reason GitHub didn't like my rebase and I couldn't get it to sync in order to update pull request. So I've just created a new request, and am closing this one.

New pull request: https://github.com/MoonchildProductions/Pale-Moon/pull/49

**Pull request closed without merging**
