### PR TITLE
Implement AbstractThread

### PR DESCRIPTION
**Pull request by trav90**
AbstractThread is a simplification of our existing MediaPromise code that (unlike MediaPromises) guarantees that two events will not run at the same time - either because it's a single thread or because it's a task queue.

Built and lightly tested on several YouTube vids and Twitch streams and appears to be working as intended.

### CODE REVIEW

**Comment by trav90** [comment]
Also worth noting: much of Mozilla's work eliminating most of the ReentrantMonitor for media support is dependent on this.

**Comment by mattatobin** [comment]
I will give this some testing on Windows, Travis.

**Comment by wolfbeast** [comment]
"Gee, Promises for everything wasn't such a good idea after all...!" - "'told you".

**Comment by mattatobin** [comment]
I like it.. However, more testing will tell. I'll let you all know..

**Comment by mattatobin** [comment]
Yeah, I recommend you can have done merge this pull request. :P

**Pull request merged**
