### PR TITLE
[!] Upstream pull of SQLite3: 3.8.8.3 -> 3.8.10.1

### PR DESCRIPTION
**Pull request by Axiomatic-**
Change log can be found here: http://www.sqlite.org/changes.html

### CODE REVIEW

**Comment by wolfbeast** [comment]
- Fix a potential 32-bit integer overflow problem
- Performance improvements (ORDER BY, VACUUM, CREATE INDEX, fts3/4 queries)
- Fix many obscure problems discovered while SQL fuzzing.

**Comment by wolfbeast** [comment]
Any idea why the sqlite.h file has so many additions? I'd like to prevent header bloat.

**Comment by wolfbeast** [comment]
I just verified the sqlite library - this pull request is obviously incorrect because the amalgamation library does not have this .h inflation.

Closing this pull.

**Comment by wolfbeast** [comment]
While I was at it and had the files downloaded anyway, I've updated the lib myself since it's a simple copy/edit operation. Sorry to go over your head :)

**Comment by Axiomatic-** [comment]
No worries, sorry about that. (Honestly I have no clue what happened, anyway glad you got to this.)

**Pull request closed without merging**
