### PR TITLE
Set release notes URL in About dialog based on channel

### PR DESCRIPTION
**Pull request by JustOff**
Original code is from [about.xhtml](http://xref.palemoon.org/palemoon-trunk/source/toolkit/content/about.xhtml) / [about.js](http://xref.palemoon.org/palemoon-trunk/source/toolkit/content/about.js)

PS: This dialog should also be properly localized, I'll prepare a separate PR.

### CODE REVIEW

**Comment by wolfbeast** [comment]
> PS: This dialog should also be properly localized, I'll prepare a separate PR.

Sorry, but it should not. I've mentioned this before. The about box should not be localized since Pale Moon is an English-language product. What people do to change their UI language doesn't change the fact that "about this software" should be in its original form at all times. The parts that matter for functionality (for updates) are already localized.

**Comment by JustOff** [comment]
Even [these lines](https://github.com/JustOff/Pale-Moon/blob/fca3f1c776c28a81c94c126a3c8b600fbffa7aeb/browser/base/content/aboutDialog.xul#L107)?
```
<label class="text-link bottom-link" href="about:license">Licensing information</label>
<label class="text-link bottom-link" href="about:rights">End-user rights</label>
<label class="text-link bottom-link" id="releaseNotesURL">Release notes</label>
```
They are localized in all other places and we already have the first two in chrome://browser/locale/aboutDialog.dtd, only the last one is missed.

**Comment by wolfbeast** [comment]
Yes, especially those lines. What do they link to? English pages. I'm NOT going to localize the website as well. This was localized at Mozilla because they have everything localized.

**Comment by JustOff** [comment]
Thanks, got it.

**Pull request merged**
