### PR TITLE
Load manifest of SDK-based addons from extension.json

### PR DESCRIPTION
**Pull request by JustOff**
This will allow to run SDK-based addons that specially targeted to Pale Moon (PMkit)

### CODE REVIEW

**Comment by JustOff** [comment]
And please add labels 'Extensions' and 'PMkit' to PRs #776, #777, #778, #780, #781, #783, #784, #785, #787, #788, #789 and to this one.

**Comment by janekptacijarabaci** [comment]
See also:
http://xref.palemoon.org/tycho-trunk/find?text=&string=package.json
http://xref.palemoon.org/tycho-trunk/search?string=package.json

**Comment by JustOff** [comment]
@janekptacijarabaci I saw, but this PR is intentionally limited by that was already included.

**Comment by JustOff** [comment]
@wolfbeast 
Please put this PR on hold for a while.

**Comment by JustOff** [comment]
@wolfbeast 
Could you please take a look to the [alternative proposal](https://forum.palemoon.org/viewtopic.php?p=102276#p102276)?

**Pull request closed without merging**
