### PR TITLE
Abstract MP4 code away from libstagefright

### PR DESCRIPTION
**Pull request by trav90**
This PR abstracts the majority of our MP4 code away from libstagefright (except for metadata), and replaces it with our own code (with more to come soon, including the glue and a demuxer for FFmpeg to work). Also wrapped up in this PR is some code cleanup of now unused stagefright code, several crash and regression fixes, and a few code styling fixes.

I've tested playing MP4, OGG, and mediasource files, as well as YouTube (both MP4 & WebM). All appears to be working as intended.

### CODE REVIEW

**Comment by wolfbeast** [comment]
Hats off to you, Travis!
Also, moving away from libstagefright is something I very much appreciate - it's been a sec vulnerability nightmare! 
I'll merge this in, and make a test build on Windows, and give it a solid thrashing on media sites.

**Comment by wolfbeast** [comment]
OK, this caused some build bustage. Can you please check?
https://gist.github.com/wolfbeast/c8c461a3fd4df7b71bcb8e615c738239

**Comment by trav90** [comment]
Submitted PR #620 which hopefully will fix it.

**Comment by wolfbeast** [comment]
Almost there. I think you overlooked the second error in the gist:

````
 1:07.03 Unified_cpp_dom_media_fmp4_wmf0.cpp
 1:07.03 e:\mozdev\TychoPM\dom\media\fmp4\wmf\WMFMediaDataDecoder.cpp(140) : error C2065: 'aSample'
: undeclared identifier
 1:07.03 e:\mozdev\TychoPM\dom\media\fmp4\wmf\WMFMediaDataDecoder.cpp(140) : error C2227: left of '-
>mOffset' must point to class/struct/union/generic type
 1:07.03         type is 'unknown-type'
````

**Comment by trav90** [comment]
Yup, totally spaced on that part. Sorry about that. :/

Submitted PR #621

**Comment by wolfbeast** [comment]
Just for a frame of reference: I assume this code is sourced in a Mozilla project somewhere (and it's not in mozilla-central) considering specific Gonk code et al. Any place where I could educate myself on the context of these commits?

**Comment by trav90** [comment]
It's may not be in moz-central anymore, but all these patches were ported from hg commits to moz-central (targeting ff 40 & 41). I'll round up some BMO numbers and post them here shortly for you to look at.

**Comment by trav90** [comment]
OK, the main bug #'s are:

1154164
1150853
1153049
1156689

The remaining commits in this PR are primarily fixing crashes/regressions introduced by the patches in the bugs listed above.

**Comment by wolfbeast** [comment]
Ah okay, I see -- so why did they move away from this again? Some political decision?
In any case, you pretty much own this module; I just want to have a grasp of what exactly is being done here and how the resulting code handles video.

I've also successfully built with PRs #620 and #621 addressed, and tested basic playback and youtube MSE+VP9, and everything seems to be a-OK with it! I'll go and visit some different sites when I've more time to do so.

**Comment by trav90** [comment]
While I don't know all the reasons, from what I understand at this point (after esr38) Mozilla was wanting to get away from relying on GStreamer (due to its increasing crashyness), but stagefright was turning out to be a pretty buggy mess itself (not to mention the security nightmare). So they decided to reduce their dependence on stagefright and start using their own code with FFmpeg (eventually).

> I've also successfully built with PRs #620 and #621 addressed...

Awesome!

**Pull request merged**
