### PR TITLE
On Aero-enabled systems, use Aero-style icons in the various Bookmarks and History menus

### PR DESCRIPTION
**Pull request by Antonius32**
This pull request replaces the default "Organize Bookmarks" and "Show All History" icons in the various Bookmarks and History menus with Aero-style versions on Aero-enabled systems.

This is a follow-up to PR #233.

### CODE REVIEW

**Comment by wolfbeast** [comment]
Maybe you can pool some of these edits together? That way the number of PRs don't get out of hand, and you can just make & test commits as-is until you're satisfied before making a PR (which in general are for completed features, not running works in progress)

**Comment by Antonius32** [comment]
Sure, I will keep that in mind next time.

**Comment by wolfbeast** [comment]
Not a complaint, just a hint :)

**Comment by Antonius32** [comment]
It's all good, I appreciate your advice!

**Pull request merged**
