### PR TITLE
Cookies - sub1.example.com vs. sub2.sub1.example.com: Forget About site (+ improvements, follow up); Permissions (+ fix comments, follow up)

### PR DESCRIPTION
**Pull request by janekptacijarabaci**
## 1)

Ad https://forum.palemoon.org/viewtopic.php?f=50&p=112386#p112386

> The `getCookiesFromHost` method will only match `sub1.example.com` and `example.com` if aDomain = 
`sub1.example.com`. It will not match `sub2.sub1.example.com`.

## 2)
Ad https://github.com/MoonchildProductions/Pale-Moon/issues/579#issuecomment-257860811

> When I want to perform that command on a site that has a large number of entries (as shown on the screenshot; I chose CNN.com for this example) in the History menu, two things happen:
> - It only deletes one or a couple of entries instead of all of them.
> - The Forget About This Site and Delete This Page commands become unresponsive. When I try to apply them to any site in the History menu, they simply won't work.
>> I don't think it works as it should with 27b3. I just tried it on my desktop and on a portable x86 on my laptop and the issue is still there.

See also:
https://bugzilla.mozilla.org/show_bug.cgi?id=1247201

---

## 3)

__3a)__
Fix Permissions - if the master password is set.

__3b)__
Follow up:
The indexOf() method is case sensitive!
`User canceled Master Password entry` !== `User canceled master password entry`

See also:
https://bugzilla.mozilla.org/show_bug.cgi?id=1358772

---

I've created the new build (x32, Windows) and tested.

### CODE REVIEW

**Comment by janekptacijarabaci** [comment]
@wolfbeast 
I propose to consider this as `Uplift Wanted` (27.3.0).

**Comment by wolfbeast** [comment]
Too late for 27.3.0 - already in RelEng stage.

**Comment by janekptacijarabaci** [comment]
Is it too late for 27.3.1 (if that will be the case)?

**Comment by wolfbeast** [comment]
I don't know if there will be a point release. if so, I'll keep it in mind.

**Pull request merged**
