### PR TITLE
Permissions - more values: Load Images, Install Addons, Hide the Mouse Pointer

### PR DESCRIPTION
**Pull request by janekptacijarabaci**
## Permissions Manager

Ad:
#639 (Add loading of images permissions)
#641 (Add installing of add-ons permissions)
#640 (Add hiding of mouse pointer permissions)

\+ style clean up - sort items (`Permissions Manager` vs. `Page Info`)

Ad (not created):
#642 (Add desktop notifications permissions)
I don't know which key you want to use... `dom.push.enabled`?
In addition, it is necessary to change more...

---

The suggestion (for example).

__It is necessary to test all options!__

---

I've created the new build (x64) and tested.

### CODE REVIEW

**Comment by wolfbeast** [comment]
I think you misunderstand what this is supposed to do.
You are dealing with site-specific preferences here, so you don't want to read or set the global preferences in the browser, but rather deal with the site-specific preferences database.

**Comment by janekptacijarabaci** [comment]
> You are dealing with site-specific preferences here, so you don't want to read or set the global preferences in the browser, but rather deal with the site-specific preferences database.

I think I'm doing... But if I have misunderstood something - you take it as an unfinished example :-)

**Comment by wolfbeast** [comment]
I'll have to check in detail when my head is on right. sorry if it'll take a bit; I'm not familiar with this specific code yet.

**Comment by wolfbeast** [comment]
After checking the overarching logic involved, this looks good. I'll merge it in and give it a test.

**Comment by janekptacijarabaci** [comment]
@JustOff 
FYI, new strings to translate (potentially):
https://github.com/MoonchildProductions/Pale-Moon/commit/629aadc1a01471d9668f926486c60159a9137f5e#diff-58ebd4ce0478b88cc49e6e016fa17b8d

**Pull request merged**
