### PR TITLE
Remove Mozilla promotional snippets

### PR DESCRIPTION
**Pull request by squarefractal**
While already disabled by way of commenting out of the element in which the snippets are disabled, this PR fully removes the snippets backend code since this is of no use for Pale Moon.

Submitting to Code_Cleanup branch as requested, but git wants to push a lot more; only the last three commits are relevant to this PR.

### CODE REVIEW

**Comment by wolfbeast** [comment]
In the future, if you want to make a PR against a master-equivalent feature branch that is behind, ping me so I can fast-forward it to keep the commits cleaner.
I don't see us using these snippets in the future, so yeah, might as well remove the redundant code from the browser ;)

**Comment by wolfbeast** [comment]
Please add a cleanup for the abouthome.xhtml as well.

**Comment by squarefractal** [comment]
_(Just in case if a notification was not generated)._

**Comment by wolfbeast** [comment]
Code edits/updates to a pull request apparently do not generate notifications, so you'll have to add a comment to be noticed.

**Pull request merged**
