### PR TITLE
[Minor fix] Importing from HTML - A bookmark loses it's description text if a separator is in place next to it

### PR DESCRIPTION
**Pull request by janekptacijarabaci**
Ad #996 

---

I've created the new build (x32, Windows) and tested.

### CODE REVIEW

**Comment by JustOff** [comment]
Are you sure this actually fixes the problem? As far as I see from `BookmarkHTMLUtils.jsm` the `DD` tag in Netscape Bookmark Format does not implied to be explicitly closed and much more crazy logic is used.

**Comment by janekptacijarabaci** [comment]
> Are you sure this actually fixes the problem?

It works for me. I am not sure if it breaks something else - but I don't know what.

**Comment by JustOff** [comment]
As far as I understand the problem is with parser, not with writer. I think we can't just change Netscape Bookmark Format, even if it's ugly.

**Comment by janekptacijarabaci** [comment]
This idea of not closing (some) tags is very strange (there may be more problems in the future).

But... I was looking for an interim solution. The simplest solution. I was not looking at it precisely.

**Comment by wolfbeast** [comment]
If there's an issue with this, it should be solved on the reading end, not the writing end, anyway. I'll take the proposed solution in #999 in favor of this, since it'll fix it for reading from old and new exports, IIUC.

**Pull request closed without merging**
