### PR TITLE
fmp4 decoder: add missing #include for mac

### PR DESCRIPTION
**Pull request by stevenschlansker**
You might want to consider this a WIP -- while it helps the build get further
along, I still don't have a successful build.

manual cherry-pick of ab938f4e956e4f53c9cec092892e9f308fcafaf9 by @trav90

### CODE REVIEW

**Comment by wolfbeast** [comment]
It may be better to simply focus on the current intended release (27.2) that I've just made a branch for. Skip 27.1 and get all the needed updates in one go ;)

**Comment by trav90** [comment]
As mentioned above, this patch doesn't fully fix building on Mac, but it does resolve the bustage reported in #927. I suggest going ahead and merging this in (with uplift to the 27.2 RelBranch would probably be good also).

This way, one of the (hopefully only) two issues with building for Mac will be resolved.

**Comment by wolfbeast** [comment]
Is an uplift OK here? Where did this bust? I ask because the latest media additions from #954 were NOT merged into `27.2_RelBranch`.

**Comment by trav90** [comment]
It should be. This was actually busted back in commit 60b158f, which didn't land until 27.1.0.

**Comment by trav90** [comment]
See also commit b5d96ee, which fixes the exact same issue, but on Windows.

**Comment by wolfbeast** [comment]
Right! uplifting.

**Comment by wolfbeast** [comment]
Uplifted in d768214

**Comment by stevenschlansker** [comment]
Thanks!

**Pull request merged**
