### PR TITLE
Remove bad e10s code from 'sdk/context-menu'

### PR DESCRIPTION
**Pull request by JustOff**
Roll back https://bugzilla.mozilla.org/show_bug.cgi?id=1060138
Roll back #778 and #780 (no longer required), also supersedes #783

### CODE REVIEW

**Comment by JustOff** [comment]
We should probably also rollback https://bugzilla.mozilla.org/show_bug.cgi?id=1023326, thus we could completely get rid of e10s frame scripts in SDK.

**Comment by wolfbeast** [comment]
Bug # 1070952 was backed out (it's an open bug)

**Comment by JustOff** [comment]
Unfortunately 1070952 was not backed out actually and it's present in our codebase, so we should deal with it by yourself.

**Comment by wolfbeast** [comment]
I see. I guess it was in the Mozilla tree for a while then before they backed it out.

**Pull request merged**
