### PR TITLE
DevTools - some fixes

### PR DESCRIPTION
**Pull request by janekptacijarabaci**
## DevTools - some fixes

__1) Eyedropper__

__2) Main menu__
(Pale Moon throws an errors in the Browser Console - see attachment - 1.)

__Before__
main-menu_001

__After__
main-menu_002

__3) Storage__
(Pale Moon throws an errors in the Browser Console - see attachment - 2.)
https://bugzilla.mozilla.org/show_bug.cgi?id=1175850

__4) ...some other__
(Pale Moon throws an errors in the Browser Console - see attachment - 3.)
See also https://bugzilla.mozilla.org/show_bug.cgi?id=1077464
(not finished - currently I don't have time - new function open() - does not work):
https://hg.mozilla.org/releases/mozilla-esr38/diff/c75d5601b154/browser/base/content/browser.js

__5) Fix typo, style clean up.__

__________
__The suggestion (for example).__

__I've created the new build (x64) and tested.__
__________
Pale Moon (27.0.0b1) throws an errors in the Browser Console:
browser-console

### CODE REVIEW

**Comment by wolfbeast** [comment]
Thanks! I was actually going to tackle this next but you got ahead of me ;)

Are you planning to address points 3 and 4, yourself, or should someone else be tackling that?
(3 seems simple -- missing l10n string?)
point 4 is actually very much optional functionality and can be removed if fixing it up is not simple - remote debugging isn't at all needed for desktop; this was added mostly for debugging b2g/Firefox OS.

**Comment by wolfbeast** [comment]
Doesn't look like this PR fixed the web developer tools menu. It still only shows the items that are in the "before" image.

**Comment by wolfbeast** [comment]
I think the problem is a missing pref. devtools.webide.widget.enabled

**Comment by wolfbeast** [comment]
That wasn't all of it, just what I saw an error for. Please see if you can figure out why the menu items won't initialize?

**Comment by janekptacijarabaci** [comment]
> Are you planning to address points 3 and 4, yourself, or should someone else be tackling that?
(3 seems simple -- missing l10n string?)

I think I described it wrong... Points 1, 2, 3 and 5 are (they should be) corrected.

> That wasn't all of it, just what I saw an error for. Please see if you can figure out why the menu items won't initialize?

We have some different settings :-/ It works for me.

> point 4 is actually very much optional functionality and can be removed if fixing it up is not simple - remote debugging isn't at all needed for desktop; this was added mostly for debugging b2g/Firefox OS.

In that case, I returned those "nasty" changes (and just shut it off).

**Comment by janekptacijarabaci** [comment]
> Point 4 is actually very much optional functionality and can be removed if fixing it up is not simple - remote debugging isn't at all needed for desktop; this was added mostly for debugging b2g/Firefox OS.

> In that case, I returned those "nasty" changes - in "/browser/devtools/performance" and "/browser/devtools/framework/toolbox.js" - and just shut it off...

@wolfbeast 
Can you revert this commit please?
I made a simple change...

If you have a simpler idea :-)

**Comment by wolfbeast** [comment]
I'll back it out. A little confused about what you propose but open to suggestions.

**Comment by wolfbeast** [comment]
Maybe it'll help if you can let me know what your settings are that make it work every time. I tried with a fresh profile and it didn't work.

**Comment by janekptacijarabaci** [comment]
You're right :-)

Issue was fixed:
https://github.com/MoonchildProductions/Pale-Moon/commit/182b30d3de72b5eb958e9e520d5b708efbea0404

**Pull request merged**
