### PR TITLE
Supports building with Clang and Libc++

### PR DESCRIPTION
**Pull request by alaviss**
I have ported some patches from gecko-dev to allow Pale Moon to be built with clang/libc++

Tested with clang 5.0.0

### CODE REVIEW

**Comment by mattatobin** [comment]
And what are the effects of these changes to gcc and msvc?

**Comment by alaviss** [comment]
I'm currently building with gcc, but I would need help in testing with msvc, as I don't use Windows

**Comment by JustOff** [comment]
I just made win32 build with this changes, it seems to run as usual.

**Comment by mattatobin** [comment]
Don't underestimate any change to jemalloc or to xpcom even the smallest thing can be disastrous even if it isn't evident at a cursory glance.

**Comment by alaviss** [comment]
Builds and runs fine with gcc-4.9. I'm typing this from that build right now

**Comment by Bfgeshka** [comment]
Tried current master with this patchset and build (still) fails on clang 4.0.

**Comment by alaviss** [comment]
Can I have the build log?

**Comment by Bfgeshka** [comment]
Here you go: http://paste.org.ru/?2p2q0f

Btw, build for gcc 6.3.0 now failed too. Build log would be in another time, but I can say that it happened in different place.

**Comment by alaviss** [comment]
Try to build with USE="-shared-js"‎

**Comment by Bfgeshka** [comment]
So far build works only for gcc 4 and 5 (not concidering clang 5 - it is so, so far in the future), which is bad because these patches are breaking more compability than bringing in. It needs to be reworked.

> Try to build with USE="-shared-js"‎

You cannot say that. Build must be able to finish successfully without dependency on specific config option set.

**Comment by wolfbeast** [comment]
I'll be backing out this patch. Sounds like you will need to make this conditional code based on which compiler and which version is in use (using preprocessor macros). You cannot simply break gcc builds (official) to satisfy clang (new support).

**Comment by alaviss** [comment]
I've pulled gcc 6.3.1 to test this, there's absolutely no build failures for gcc 6. I would be interested in build log showing build failure for gcc 6

**Comment by mattatobin** [comment]
Just ifdef it with else being the previous code. It isn't complicated.

**Pull request merged**
