### PR TITLE
FFmpeg fixes

### PR DESCRIPTION
**Pull request by trav90**
First batch of fixes! This PR adds a method of determining the version of libavcodec that is available, removes our dependence on libavformat, and fixes several FFmpeg-related bugs and crashes.

### CODE REVIEW

**Comment by JustOff** [comment]
can't build with that (win32):

```
12:34.14 Unified_cpp_media_platforms_wmf0.cpp
12:34.14 e:\Pale-Moon\dom\media\platforms\wmf\WMFVideoMFTManager.cpp(243) : error C2248: 'mozilla::MediaRawData::mData'
: cannot access private member declared in class 'mozilla::MediaRawData'
12:34.14         e:\pale-moon-build\dist\include\MediaData.h(404) : see declaration of 'mozilla::MediaRawData::mData'
12:34.14         e:\pale-moon-build\dist\include\MediaData.h(373) : see declaration of 'mozilla::MediaRawData'
12:34.14 e:\Pale-Moon\dom\media\platforms\wmf\WMFVideoMFTManager.cpp(244) : error C2248: 'mozilla::MediaRawData::mSize'
: cannot access private member declared in class 'mozilla::MediaRawData'
12:34.14         e:\pale-moon-build\dist\include\MediaData.h(405) : see declaration of 'mozilla::MediaRawData::mSize'
12:34.14         e:\pale-moon-build\dist\include\MediaData.h(373) : see declaration of 'mozilla::MediaRawData'
12:34.16
12:34.18 In the directory  /e/Pale-Moon-build/dom/media/platforms/wmf
12:34.19 The following command failed to execute properly:
12:34.19 e:/Pale-Moon-build/_virtualenv/Scripts/python.exe -m mozbuild.action.cl cl -FoUnified_cpp_media_platforms_wmf0.
obj -c -I../../../../dist/stl_wrappers -DMOZILLA_INTERNAL_API -DIMPL_LIBXUL -DAB_CD=en-US -DNO_NSPR_10_SUPPORT -Ie:/Pale
-Moon/dom/media/platforms/wmf -I. -I../../../../dist/include -Ie:/Pale-Moon-build/dist/include/nspr -Ie:/Pale-Moon-build
/dist/include/nss -MD -FI ../../../../dist/include/mozilla-config.h -DMOZILLA_CLIENT -TP -nologo -D_HAS_EXCEPTIONS=0 -W3
 -Gy -FS -wd4251 -wd4244 -wd4267 -wd4345 -wd4351 -wd4482 -wd4800 -wd4819 -we4553 -GR- -DNDEBUG -DTRIMMED -Zi -UDEBUG -DN
DEBUG -O2 -Oy -Ie:/Pale-Moon-build/dist/include/cairo -Fdgenerated.pdb e:/Pale-Moon-build/dom/media/platforms/wmf/Unifie
d_cpp_media_platforms_wmf0.cpp
12:34.19 e:/Pale-Moon/config/rules.mk:936: recipe for target 'Unified_cpp_media_platforms_wmf0.obj' failed
12:34.20 mozmake.EXE[5]: *** [Unified_cpp_media_platforms_wmf0.obj] Error 1
12:34.20 e:/Pale-Moon/config/recurse.mk:74: recipe for target 'dom/media/platforms/wmf/target' failed
12:34.20 mozmake.EXE[4]: *** [dom/media/platforms/wmf/target] Error 2
```

**Comment by trav90** [comment]
Nothing in this PR should have affected building on Windows.

**Comment by trav90** [comment]
Looks like this is caused by PR #720 - I missed making required changes in WMFVideoMFTManager.cpp

**Comment by trav90** [comment]
Created PR #727

**Comment by JustOff** [comment]
Thanks!

**Pull request merged**
