### PR TITLE
[suggestion] Security - added support for TLS 1.3

### PR DESCRIPTION
**Pull request by janekptacijarabaci**
Ad:
https://forum.palemoon.org/viewtopic.php?f=26&t=12433
(and of course: https://github.com/MoonchildProductions/Pale-Moon/commit/f4fb488471eb4a4689531d2ae698c45a8839d8d2)

It's only a draft:
https://tlswg.github.io/tls13-spec/
but it is "opt-in" (for a tests).

See (the basic part):
https://bugzilla.mozilla.org/show_bug.cgi?id=1250568
https://bugzilla.mozilla.org/show_bug.cgi?id=1275252
https://bugzilla.mozilla.org/show_bug.cgi?id=1250582
https://bugzilla.mozilla.org/show_bug.cgi?id=1304919

See (the next part):
https://bugzilla.mozilla.org/show_bug.cgi?id=1264578
https://bugzilla.mozilla.org/show_bug.cgi?id=1340164
https://bugzilla.mozilla.org/show_bug.cgi?id=1343600

A basic test TLS 1.3, e.g.:
https://blog.cloudflare.com/introducing-tls-1-3/
https://tls13.cloudflare.com/
https://tls13.crypto.mozilla.org/

---

__See also:__
https://bugzilla.mozilla.org/show_bug.cgi?id=1337791
__But it is not implemented...__

---

__All such changes need to be thoroughly verified.__

__You add the label `Verification needed`, please.__

---

I've created the new build (x32, Windows) and tested.

### CODE REVIEW

**Comment by wolfbeast** [comment]
Is this still WIP or is it ready to be merged?

**Comment by janekptacijarabaci** [comment]
It is ready to be merged. And for thorough testing (including "older" TLS/protocols - 1.2 etc., of course).

**Comment by wolfbeast** [comment]
Currently, setting `security.tls.version.max` to `4` causes issues; the browser does not properly initialize.
Can you please investigate?

**Comment by wolfbeast** [comment]
Staring with -jsconsole provides the following:
````
Timestamp: 27/04/2017 02:54:06
Error: NS_ERROR_XPC_GS_RETURNED_FAILURE: Component returned failure code: 0x80570016 (NS_ERROR_XPC_GS_RETURNED_FAILURE) [nsIJSCID.getService]
Source File: file:///e:/mozdev/PaleMoon/build-x86-unstable/dist/bin/components/crypto-SDR.js
Line: 79
Timestamp: 27/04/2017 02:54:06
Error: uncaught exception: Initialization failed
Timestamp: 27/04/2017 02:54:06
Error: NS_ERROR_XPC_JS_THREW_STRING: Initialization failed'Initialization failed' when calling method: [nsILoginManagerStorage::initialize]
Source File: file:///e:/mozdev/PaleMoon/build-x86-unstable/dist/bin/components/nsLoginManager.js
Line: 156
Timestamp: 27/04/2017 02:54:06
Error: NS_ERROR_XPC_GS_RETURNED_FAILURE: Component returned failure code: 0x80570016 (NS_ERROR_XPC_GS_RETURNED_FAILURE) [nsIJSCID.getService]
Source File: resource://gre/modules/XPCOMUtils.jsm
Line: 218
Timestamp: 27/04/2017 02:54:06
Error: NS_ERROR_XPC_CI_RETURNED_FAILURE: Component returned failure code: 0x80570015 (NS_ERROR_XPC_CI_RETURNED_FAILURE) [nsIJSCID.createInstance]
Source File: file:///e:/mozdev/PaleMoon/build-x86-unstable/dist/bin/components/nsSearchService.js
Line: 4108
Timestamp: 27/04/2017 02:54:06
Error: NS_ERROR_XPC_CI_RETURNED_FAILURE: Component returned failure code: 0x80570015 (NS_ERROR_XPC_CI_RETURNED_FAILURE) [nsIJSCID.createInstance]
Source File: file:///e:/mozdev/PaleMoon/build-x86-unstable/dist/bin/components/nsSearchService.js
Line: 4108
Timestamp: 27/04/2017 02:54:06
Error: NS_ERROR_XPC_CI_RETURNED_FAILURE: Component returned failure code: 0x80570015 (NS_ERROR_XPC_CI_RETURNED_FAILURE) [nsIJSCID.createInstance]
Source File: file:///e:/mozdev/PaleMoon/build-x86-unstable/dist/bin/components/nsSearchService.js
Line: 4108
Timestamp: 27/04/2017 02:54:06
Error: NS_ERROR_XPC_CI_RETURNED_FAILURE: Component returned failure code: 0x80570015 (NS_ERROR_XPC_CI_RETURNED_FAILURE) [nsIJSCID.createInstance]
Source File: file:///e:/mozdev/PaleMoon/build-x86-unstable/dist/bin/components/nsSearchService.js
Line: 4108
Timestamp: 27/04/2017 02:54:06
Error: [Exception... "Component returned failure code: 0x80570015 (NS_ERROR_XPC_CI_RETURNED_FAILURE) [nsIJSCID.createInstance]"  nsresult: "0x80570015 (NS_ERROR_XPC_CI_RETURNED_FAILURE)"  location: "JS frame :: file:///e:/mozdev/PaleMoon/build-x86-unstable/dist/bin/components/nsSearchService.js :: SRCH_SVC__getVerificationHash :: line 4108"  data: no]
Source File: file:///e:/mozdev/PaleMoon/build-x86-unstable/dist/bin/components/nsSearchService.js
Line: 4145
````

**Comment by janekptacijarabaci** [comment]
That's strange, I do not have this problem :-/
I try to build (Windows, x32 - totally clean assembly process - the `obj-i686-pc-mingw32` directory does not exist) the Pale Moon from master branch (latest) and after use of:
`palemoon.exe -jsconsole`
run without errors:

**Comment by janekptacijarabaci** [comment]
Some cache problem?

See e.g.:
http://webcache.googleusercontent.com/search?q=cache:tqiGmjUgnHkJ:forums.mozillazine.org/viewtopic.php%3Ff%3D39%26t%3D2261855+

**Comment by JustOff** [comment]
> Currently, setting security.tls.version.max to 4 causes issues; the browser does not properly initialize.

I confirm that clobber build fixes this problem.

**Comment by wolfbeast** [comment]
Check.
Clobber build required, enforced through 351a0ccdbdf6e8c8c5f50eec5aa5ebbc633c7435

**Comment by wolfbeast** [comment]
This has been live on our builds for a while now, considering this fully verified.

**Pull request merged**
