### PR TITLE
Allow imagedocument.png to be themeable

### PR DESCRIPTION
**Pull request by FranklinDM**
Includes imagedocument.png to the base theme and allows it to be theme-able by custom themes.
(hasn't been tested yet)

### CODE REVIEW

**Comment by wolfbeast** [comment]
@Lootyhoof This would probably require changes to all themes, correct?

**Comment by Lootyhoof** [comment]
Correct. As this change appears to be related specifically to the favicon shown in the urlbar (though not the tab), when viewing a standalone image, the effects should be minimal (a missing favicon in the urlbar perhaps).

**Comment by Lootyhoof** [comment]
As an aside, it looks like this icon is not included in each platform's `jar.mn` yet, so wouldn't be included in the processed build. These can be found at:

`/browser/themes/*/jar.mn`

**Comment by FranklinDM** [comment]
Thanks. Sorry, I didn't really know much about these since I'm just new to this (can't clone the repo & test, data caps).

**Comment by Lootyhoof** [comment]
Looks good to me!

**Pull request merged**
