### PR TITLE
Page Info - indexedDB - a remnant from ancient times (reversed value)

### PR DESCRIPTION
**Pull request by janekptacijarabaci**
See also https://github.com/MoonchildProductions/Pale-Moon/issues/1112 (but this problem remains)

---

I've created the new build (x32, Windows) and tested.

### CODE REVIEW

**Comment by wolfbeast** [comment]
I'm confused here. what exactly are you doing?

**Comment by janekptacijarabaci** [comment]
I don't see anything older:
https://github.com/MoonchildProductions/Pale-Moon/blob/24.6_RelBranch/browser/base/content/pageinfo/pageInfo.xul#L378

I don't know why it was there.

http://xref.palemoon.org/mozilla-esr24/source/browser/base/content/pageinfo/pageInfo.xul#378
vs.
https://hg.mozilla.org/releases/mozilla-esr24/annotate/tip/browser/base/content/pageinfo/pageInfo.xul#l402

IMHO: Now it's bad.

**Comment by wolfbeast** [comment]
I still don't understand what you're doing here "Now it's bad" doesn't help me to understand. If the order is visually swapped, then it would not look nice in the info window.

**Comment by janekptacijarabaci** [comment]
> If the order is visually swapped

But it is not, there would be a reversal of **values**:

Now:


After:

**Comment by wolfbeast** [comment]
Ahh I see.

**Comment by wolfbeast** [comment]
Begs the question... are you sure this corrects something wrong? because the mercurial link is only a 2-state so it was changed somewhere. Are you sure you're not breaking something here?

**Comment by janekptacijarabaci** [comment]
The mercurial :-/ link is wrong (I'm sorry):
https://hg.mozilla.org/releases/mozilla-esr24/file (a v14)
https://hg.mozilla.org/releases/mozilla-esr24/file/8a82039ef232 (a last v24)

However...

Here it is added:
https://hg.mozilla.org/mozilla-central/rev/e7ccacd50d63
a here it was removed: 
https://hg.mozilla.org/mozilla-central/rev/8bcb8d073908

IMHO: It has three possible values (for a very long time).

An example:
http://clb.demon.fi/dump/html5_popups/?persistent
(there is a difference between `Always ask` and `Allow`)

**Pull request merged**
