### PR TITLE
Fix MOZ_NATIVE_JEMALLOC

### PR DESCRIPTION
**Pull request by jbeich**

### CODE REVIEW

**Comment by wolfbeast** [comment]
Sorry, no. I can't accept this.
Old versions of system jemalloc are not supported. Using jemalloc3 implies using the in-tree version.

**Comment by jbeich** [comment]
How old? FreeBSD 11.0 has jemalloc 4.2.1. This PR doesn't enable system jemalloc by default.

**Comment by wolfbeast** [comment]
Then please provide a description what you're doing here and why.

**Comment by jbeich** [comment]
If not obvious from reading commit messages and maybe following bug references:
- c9eccd1e4 fixes 4d9fe80 regression
- cece2ee fixes 9df3bfd regression

**Comment by wolfbeast** [comment]
Considering ragequit and deleted repo, reopening is not possible.
Don't let the door hit you on the way out.

**Pull request closed without merging**
