### PR TITLE
Add option to toggle Ctrl+Tab previews in Preferences

### LINKED ISSUE #1444: Add an option to tab preferences to switch previews on/off
Since it remains a common question for people, we should expose `browser.ctrlTab.previews` in the UI.

This is a good first issue for new contributors.

### PR DESCRIPTION
**Pull request by SpockMan02**
This resolves #1444.

### CODE REVIEW

**Comment by JustOff** [comment]
> `"Show tab previews when switching tabs with Ctrl+Tab"`

Until I sent this update to the translators, I thought maybe it'd be better to omit re-mentioning of tabs, i.e. just say `"Show tab previews when switching with Ctrl+Tab"`?

**Comment by mattatobin** [comment]
"Show previews when switching tabs with Ctrl+Tab" is superior phrasing.

**Comment by wolfbeast** [comment]
Yeah one "tabs" too many.

> "Show previews when switching tabs with Ctrl+Tab" is superior phrasing.

I have to agree.

**Comment by JustOff** [comment]
Thanks, the updated string was added for translation.

**Pull request merged**
