### PR TITLE
CSS: Percentage max-width does not seem to affect contributions to intrinsic min-width

### PR DESCRIPTION
**Pull request by janekptacijarabaci**
Ad https://forum.palemoon.org/viewtopic.php?f=26&p=102056

---

Last bad: Firefox 46.0a2 (2016-02-09)
Built from https://hg.mozilla.org/releases/mozilla-aurora/rev/6a9b6a1e24545e0836150269df83bc53bea0db2d

First good: Firefox 46.0a2 (2016-02-10)
Built from https://hg.mozilla.org/releases/mozilla-aurora/rev/274c4d8b82caf0d7166b914e6772a6d1c4ca167b

Pushlog
http://hg.mozilla.org/releases/mozilla-aurora/pushloghtml?fromchange=6a9b6a1e24545e0836150269df83bc53bea0db2d&tochange=274c4d8b82caf0d7166b914e6772a6d1c4ca167b

See:
https://bugzilla.mozilla.org/show_bug.cgi?id=823483
See also:
https://bugzilla.mozilla.org/show_bug.cgi?id=1174450
(https://hg.mozilla.org/mozilla-central/diff/06f474c578d6/layout/base/nsLayoutUtils.cpp)

---

I've created the new build (x64) and tested.

__But please check it in detail (all options).__

### CODE REVIEW

**Comment by wolfbeast** [comment]
Oh, Mozilla finally got around to addressing that? That's good. Thanks for porting this across!

**Comment by wolfbeast** [comment]
Bug 1174450 doesn't seem to apply to us -- is that a regression from 823483?

**Comment by janekptacijarabaci** [comment]
> Bug 1174450 doesn't seem to apply to us

I added it for context.

https://hg.mozilla.org/mozilla-central/diff/06f474c578d6/layout/base/nsLayoutUtils.cpp#l1.264
vs.
https://hg.mozilla.org/mozilla-central/rev/b34ebd7afb78#l1.3

It has no other reason.

**Comment by wolfbeast** [comment]
More mindless renaming/refactoring then.

**Pull request merged**
