### PR TITLE
Brotli Accept-Encoding/Content-Encoding #921

### PR DESCRIPTION
**Pull request by Gpower2**
Enable Brotli Accept-Encoding/Content-Encoding
Ported bugs: 366559, 1211916, 1211580

Tested and it works like a charm!
Test page: https://www.iisbrotli.com/support

PS. Sorry for the messy PR, I've been working on this for quite some time with a lot of breaks in between.
Fortunately, only the correct files are touched.

### CODE REVIEW

**Comment by janekptacijarabaci** [comment]
See also [bug 1224291](https://bugzilla.mozilla.org/show_bug.cgi?id=1224291) ([bug 1243724](https://bugzilla.mozilla.org/show_bug.cgi?id=1243724)).
AFAIK (I don't known if it's needed).

**Comment by Gpower2** [comment]
These do not apply for the version of Brotli that is used with this PR. ;)
I do intend on porting 1340910 which updates Brotli to v0.6 and was completed only 5 days ago,
however I don't currently have the time to carefully port it, so something to wait for in the future! :)

**Comment by wolfbeast** [comment]
Unfortunately Brotli 0.6 will be required to avoid a few sec issues. I'm not comfortable enabling a pre-0.6 version in Pale Moon. So please add the update to 0.6 when you can and then ping me to merge it!

**Comment by wolfbeast** [comment]
Ah wait scratch that. seems that 0.4 is fine for now.

**Comment by wolfbeast** [comment]
Merging this in. Use #1290 and #1291 to address the lib updates needed for WOFF2/Brotli.

**Comment by wolfbeast** [comment]
Unfortunately it doesn't "work like a charm" on real sites. It causes no-content responses on Facebook and Google Search if enabled. There are likely some follow-up bugs that need porting; I've removed the accept-encoding header from the prefs on trunk for now until this is sorted out.

**Pull request merged**
