### PR TITLE
Tabs - support for "Duplicate Tab"

### PR DESCRIPTION
**Pull request by janekptacijarabaci**
See:
https://bugzilla.mozilla.org/show_bug.cgi?id=455722

---

You add the label `String changes`, please.

---

I've created the new build (x32, Windows) and tested.

### CODE REVIEW

**Comment by JustOff** [comment]
9 years old bug, OMFG ... 

PS: Are you sure this feature is really useful? :stuck_out_tongue_winking_eye:

**Comment by janekptacijarabaci** [comment]
> Are you sure this feature is really useful?

IMHO: Certainly.

**Comment by wolfbeast** [comment]
Um...
Hold ctrl and drag the tab, and there you go. There's no need for this.

**Comment by wolfbeast** [comment]
FTR for future requests for this: the community was given open vote on this and it was voted against.
https://forum.palemoon.org/viewtopic.php?f=5&t=23791&start=20

**Pull request closed without merging**
