### PR TITLE
Crypto Services (utils): Support for SHA224-512 (+ fix typo)

### PR DESCRIPTION
**Pull request by janekptacijarabaci**
## 1) Support for SHA224-512:

__An example - steps to reproduce:__

1) Open Scratchpad
2) Menu: "Environment-Browser"
3) Insert the code:
``` javascript
Components.utils.import("resource://services-common/utils.js");
Components.utils.import("resource://services-crypto/utils.js");

let str = "some characters";

let shaX = ["1", "256", "384", "512", "224"];

let alertsStr = [];
for (let shaIdx = 0, shaIdxLen = shaX.length; shaIdx < shaIdxLen; shaIdx++) {
  let shaXIdx = shaX[shaIdx];

  alertsStr.push(
      "CryptoUtils.sha" + shaXIdx + ":\n" +
      CryptoUtils["sha" + shaXIdx](str) + "\n" +
      "CryptoUtils.UTF8AndSHA" + shaXIdx + ":\n" +
      CryptoUtils["UTF8AndSHA" + shaXIdx](str) + "\n" +
      "CryptoUtils.sha" + shaXIdx + "Base32:\n" +
      CryptoUtils["sha" + shaXIdx + "Base32"](str) + "\n" +
      "CommonUtils.decodeBase32:\n" +
      CommonUtils.decodeBase32(CryptoUtils["sha" + shaXIdx + "Base32"](str)) + "\n\n"
  );
}

console.log(alertsStr.join(""));
```
4) Run

See also:
https://hg.mozilla.org/mozilla-central/rev/0123be9d2c87#l1.12

## 2) Fix typo:

__An example - steps to reproduce:__

1) Open Scratchpad
2) Menu: "Environment-Browser"
3) Insert the code:
``` javascript
Components.utils.import("resource://services-crypto/utils.js");
alert(CryptoUtils.pbkdf2Generate("phrase", "a", 4096, null));
```
4) Run

Throws an error in Browser Console:
```
Exception: ReferenceError: SYNC_KEY_DECODED_LENGTH is not defined
pbkdf2Generate@resource://services-crypto/utils.js:185:7
```
See:
https://hg.mozilla.org/mozilla-central/rev/f3741ccc800b#l9.30
(https://bugzilla.mozilla.org/show_bug.cgi?id=1333044#c16)

---

I've created the new build (x32, Windows) and tested.

### CODE REVIEW

**Comment by wolfbeast** [comment]
Front-end hookup of existing platform functionality! \o/

**Comment by janekptacijarabaci** [comment]
@wolfbeast
I suggest reopening and adding the label `UXP-task`.

**Comment by JustOff** [comment]
Btw, what does `UXP-task` mean?)

**Comment by wolfbeast** [comment]
It's a label to keep tabs on what we need to check for the new platform.

**Pull request merged**
