### PR TITLE
Add support for Element.insertAdjacentText() and Element.insertAdjacentElement()

### PR DESCRIPTION
**Pull request by janekptacijarabaci**
Ad #871 (https://forum.palemoon.org/viewtopic.php?f=29&t=14663)

__Steps to reproduce:__
Go to: https://www.dotnetperls.com/

Throws an error in Browser Console:
```
TypeError: b.insertAdjacentText is not a function
i.js:1:331
```
---

I've created the new build (x32, Windows) and tested.

See also:
https://w3c-test.org/dom/nodes/insert-adjacent.html
http://tests.caniuse.com/?feat=insert-adjacent

__But... Please you check tests (mainly the file: `interfaces.html.ini`).__

### CODE REVIEW

**Comment by wolfbeast** [comment]
LGTM, the interfaces html has 2 tests added for the two new functions, and the numbers were increased by 2, so that's correct AFAIU.

**Comment by wolfbeast** [comment]
> I've created the new build (x32, Windows) and tested.

And yet that wouldn't have succeeded with the RefPtr/nsRefPtr mixup in your patch (see #880 and #881)... Are you sure your test builds are done correctly?

**Comment by trav90** [comment]
> And yet that wouldn't have succeeded with the RefPtr/nsRefPtr mixup in your patch

The last couple times the RefPtr/nsRefPtr mixup has happened, it didn't affect Windows. I don't know why MSVC doesn't choke on it like GCC does.

**Comment by janekptacijarabaci** [comment]
@wolfbeast 
> Are you sure your test builds are done correctly?

I am sure.

> => The last couple times the RefPtr/nsRefPtr mixup has happened, it didn't affect Windows. I don't know why MSVC doesn't choke on it like GCC does.

@trav90 
But thank you for your quick patch...

**Pull request merged**
