### PR TITLE
Clear QuotaManager storage along with Offline Website Data

### PR DESCRIPTION
**Pull request by JustOff**
* If 'Offline Website Data' is selected to be cleared when Pale Moon closes, then QuotaManager data (IndexedDB and asm.js cache) should be removed as well
* If you manually clear the history (Ctrl+Shift+Del) with time range set to 'Everything' when 'Offline Website Data' is selected, then QuotaManager data should be also removed

See forum topics ([1](https://forum.palemoon.org/viewtopic.php?f=3&t=16736), [2](https://forum.palemoon.org/viewtopic.php?f=13&t=16198)) and [bug #1047098](https://bugzilla.mozilla.org/show_bug.cgi?id=1047098) (currently it's a [blocker](https://bugzilla.mozilla.org/show_bug.cgi?id=1047098#c41) for the upcoming firefox56).

### CODE REVIEW

**Comment by wolfbeast** [comment]
If verified, I'll consider this uplift material for 27.5 (needs to be verified latest Sep 22nd).
I'll make an unstable build with this merged.

**Comment by JustOff** [comment]
I verified this using my local build before submit the PR, but it would be nice to get at least one independent confirmation.

**Comment by JustOff** [comment]
Two confirmations have been received: https://forum.palemoon.org/viewtopic.php?p=122402#p122402.

**Comment by wolfbeast** [comment]
Great! uplifting.

**Comment by wolfbeast** [comment]
Uplifted in 625fa2c7d29323f25c43c9af1a51e70aff95d744

**Pull request merged**
