### PR TITLE
Try to fix Mac screensaver improvements, #301

### PR DESCRIPTION
**Pull request by stevenschlansker**
Should this be NS_IMPL_ISUPPORTS1?  Seems to compile now, at least

### CODE REVIEW

**Comment by stevenschlansker** [comment]
If this PR is accepted, it obsoletes #319

**Comment by stevenschlansker** [comment]
cc @trav90 @Axiomatic-

**Comment by Axiomatic-** [comment]
Yeah, seems like this is the proper way (cannot give 100% assurance though) to my understanding, NS_IMPL_ISUPPORTSn, where n is the number of interfaces created. (This is a macro no?)

**Comment by stevenschlansker** [comment]
I am making a build now and will be testing shortly.  I'm not sure exactly what to test, so as long as it compiles and doesn't crash quickly, I'm going to push for this instead of reverting.  Progress ;)

**Comment by stevenschlansker** [comment]
Seems to work OK so far!

**Comment by Axiomatic-** [comment]
The way to test this is set your screensaver to some low amount, then open an HTML5 video and play it. What should happen is the screensaver is inhibited, if the screensaver still shows up while the video is playing then it does not work.

**Comment by wolfbeast** [comment]
Ping. 
I gather this works as-intended, then?

**Comment by stevenschlansker** [comment]
The build works OK.  I have yet to test HTML5 video, because the browser crashes on youtube :(
So I'll follow up once I get that figured out.

**Comment by trav90** [comment]
> The build works OK. I have yet to test HTML5 video, because the browser crashes on youtube :(

This is why the screensaver changes had to be backed out for Linux as well.

**Comment by wolfbeast** [comment]
This didn't actually fix the crash issues, so closing this PR in lieu of a different solution or a backout PR.

**Pull request closed without merging**
