### PR TITLE
JS - DOM - node - implement DOM4 methods: prepend(), append(), before(), after() and replaceWith() (partially)

### PR DESCRIPTION
**Pull request by janekptacijarabaci**
Ad #1410 (#1409)

See:

https://bugzilla.mozilla.org/show_bug.cgi?id=911477
https://bugzilla.mozilla.org/show_bug.cgi?id=1301777

https://bugzilla.mozilla.org/show_bug.cgi?id=1308922 (partially - follow up (?)):

__Are these changes correct?__
https://github.com/MoonchildProductions/Pale-Moon/commit/afaa122df5a839ccf1e5c6cd8f6ce548c35fc741#diff-9dc8f8c6d5d189b71696d2f9a06188d4L3365
https://github.com/MoonchildProductions/Pale-Moon/commit/afaa122df5a839ccf1e5c6cd8f6ce548c35fc741#diff-9dc8f8c6d5d189b71696d2f9a06188d4L3372

https://bugzilla.mozilla.org/show_bug.cgi?id=1104955 (partially - without `Symbol.unscopables`)

\+`RefPtr` => `nsRefPtr`

---

I've created the new build (x32, Windows) and tested:

https://developer.mozilla.org/en-US/docs/Web/API/ParentNode/prepend#Examples
https://developer.mozilla.org/en-US/docs/Web/API/ParentNode/append#Examples
https://developer.mozilla.org/en-US/docs/Web/API/ChildNode/before#Examples
https://developer.mozilla.org/en-US/docs/Web/API/ChildNode/after#Examples
https://developer.mozilla.org/en-US/docs/Web/API/ChildNode/replaceWith#Examples

### CODE REVIEW

**Comment by trav90** [comment]
@janekptacijarabaci looks like this causes build bustage on Linux with GCC 4.9:

https://gist.github.com/trav90/917722e79b9df095a5f714214f132742

**Comment by janekptacijarabaci** [comment]
@trav90 
Yes, it is possible. But I do not build on Linux. Can you try to fix it please?

**Comment by janekptacijarabaci** [comment]
@trav90 
Maybe see also: https://github.com/janekptacijarabaci/Pale-Moon/commit/68f397a5677c91d7831994d2d539859cd3c0b5f1
On Windows it works as expected.

**Comment by wolfbeast** [comment]
I'm gathering thet `getAsNode()` doesn't have a provision to return a pointer type and will therefore return an object type. MSVC is obviously smart enough to convert this implicitly, but I guess gcc needs an explicit typecast.

Does gcc like the following?:
```C++
static already_AddRefed<nsINode>
GetNodeFromNodeOrString(const OwningNodeOrString& aNode,
                        nsIDocument* aDocument)
{
  if (aNode.IsNode()) {
    nsCOMPtr<nsINode> node = static_cast<nsCOMPtr<nsINode>>(aNode.GetAsNode());
    return node.forget();
  }

  if (aNode.IsString()){
    nsRefPtr<nsTextNode> textNode =
      aDocument->CreateTextNode(aNode.GetAsString());
    return textNode.forget();
  }

  MOZ_CRASH("Impossible type");
}
```

Specifically, I added a cast: `static_cast<nsCOMPtr<nsINode>>(aNode.GetAsNode());` instead of the direct assignment.

**Comment by trav90** [comment]
@wolfbeast looks like you were right. I've submitted #1415 to resolve this.

**Pull request merged**
