### PR TITLE
aboutDialog: more architectural detection

### PR DESCRIPTION
**Pull request by MingcongBai**

### CODE REVIEW

**Comment by wolfbeast** [comment]
I've thought about this some more and I don't think it'd be a good place to do this kind of geek-level detection.
It's probably just better to generalize it to architecture-independent bit-ness statements instead of trying to bake in all theoretically possible architectures for our browser about box.
This kind of statement is probably better placed in about:support or about:buildconfig if we really want it.

**Comment by MingcongBai** [comment]
> It's probably just better to generalize it to architecture-independent bit-ness statements instead of trying to bake in all theoretically possible architectures for our browser about box.

I do agree. I will change the PR now.

**Comment by MingcongBai** [comment]
Done.

**Comment by wolfbeast** [comment]
Nit: "bit" shouldn't be capitalized.

**Comment by MingcongBai** [comment]
Good?

**Comment by wolfbeast** [comment]
Yes! Thanks :)

**Comment by wolfbeast** [comment]
This resolves #708.

**Pull request merged**
