### PR TITLE
[suggestion]: Remove healthreport, datareport

### PR DESCRIPTION
**Pull request by janekptacijarabaci**
Only for the desktop client.

__Telemetry is more challenging. I could do at least part of this. If you don't plan it (soon).__

See also #34

---

I've created the new build (x64) and tested.

__But please check it in detail.__

### CODE REVIEW

**Comment by wolfbeast** [comment]
Telemetry is extremely invasive and will need to be handled extremely carefully. It can cause very hard-to-track bugs in the browser. Be aware that that is a very large task, and if you plan to undertake it, let me know; I'll make a telemetry-work branch in that case that you can work in instead of pulling against master, to keep risks to a minimum.

**Comment by janekptacijarabaci** [comment]
> Telemetry is extremely invasive and will need to be handled extremely carefully. It can cause very hard-to-track bugs in the browser. Be aware that that is a very large task, and if you plan to undertake it, let me know; I'll make a telemetry-work branch in that case that you can work in instead of pulling against master, to keep risks to a minimum.

I would make at least some of the telemetrics. I don't know if it's enough to create a new branch...
I don't even know how much I make.

**Comment by wolfbeast** [comment]
We've axed telemetry before (unfortunately it'll have to be done again on the platform side with the re-base) and maybe you can look through commit history to see what all was done so you have an idea if you can take #34 on or not.

**Comment by janekptacijarabaci** [comment]
> if you can take #34

IMHO/AFAIK: An individual part can be used, e.g.:
TelemetryAccumulate
TelemetryStopwatch
RecordShutdown...
TelemetryTimestamps
TelemetryPing
ProcessedStack.h (maybe)

It may prove to be wrong, of course.

**Comment by janekptacijarabaci** [comment]
...also `Crash Reporter` isn't completely cleared, see also:
https://github.com/MoonchildProductions/Pale-Moon/commit/b22832b4a82f22f9f9c3440e5ad5e87266f77660

I mentioned it only :-)

**Comment by wolfbeast** [comment]
I'm going to close this PR for now but do keep it for reference. It's got a bunch of different things mixed in (crash reporter doesn't mean telemetry/health report). It should be done one step/component at a time when possible.

Sorry for not accepting it as-is; I appreciate the work, but I want to be super careful here -- it's broken the browser before when not doing it just perfect and slowly.

**Comment by janekptacijarabaci** [comment]
> Sorry for not accepting it as-is; I appreciate the work, but I want to be super careful here -- it's broken the browser before when not doing it just perfect and slowly.

Of course, it's okay :-)

**Pull request closed without merging**
