### PR TITLE
Fix vector leaks and append calls

### PR DESCRIPTION
**Pull request by janekptacijarabaci**
Ad https://github.com/MoonchildProductions/Pale-Moon/issues/1254

See:
https://bugzilla.mozilla.org/show_bug.cgi?id=1231224

Ad https://hg.mozilla.org/mozilla-central/rev/6d6334c0964f
__Note that this is only partial implementation!__
(https://bugzilla.mozilla.org/show_bug.cgi?id=1234402
\- https://hg.mozilla.org/mozilla-central/rev/a1c4a945741f)
After full implementation - a problem with build on:
https://github.com/MoonchildProductions/Pale-Moon/blob/27.4.0_Release/js/src/irregexp/RegExpEngine.cpp#L1004

---

__Patches must be thoroughly (checked and) tested!__

---

I've created the new build (x32, Windows) and tested.

### CODE REVIEW

**Comment by wolfbeast** [comment]
Can you indicate please what you ran into in your full implementation? What exactly didn't you implement of the changeset? What error did you run into?

**Comment by janekptacijarabaci** [comment]
Full implementation = https://hg.mozilla.org/mozilla-central/rev/6d6334c0964f

```
[drive]:\[path]\js\src\irregexp/RegExpEngine.cpp(1004) :
error C3861: 'Move': identifier not found
```
This variable (`new_alternatives`) does not exist
(after: https://github.com/MoonchildProductions/Pale-Moon/blob/27.4.0_Release/js/src/irregexp/RegExpEngine.cpp#L993).

**Comment by wolfbeast** [comment]
Sorry but I don't understand the issue. Those lines aren't touched by the changeset you linked to (only the RAII removal is applicable there which may not be present in our implementation to begin with)

Please indicate exactly what you did NOT implement and why.

**Comment by janekptacijarabaci** [comment]
I didn't implement the following:
https://hg.mozilla.org/mozilla-central/rev/6d6334c0964f

It gives the error already mentioned. And yes, I do not see any sense in it. You can try it out by building it.

**Comment by wolfbeast** [comment]
Well, it's not exactly important. Most likely we are using a different version of irregexp anyway (which is third party code and actually not sticking to regex standards as well, but it's what websites expect) and it's just for suppression of warnings, so we can leave it as is and call it done for the day.

**Pull request merged**
