### PR TITLE
Fix crash in MFR

### LINKED ISSUE #896: Crash in MediaTaskQueue::Dispatch
@trav90 this is your code, apparently causing crashes, possible UAF going on.

See also https://forum.palemoon.org/viewtopic.php?f=15&t=14808 for an example, and I've seen the "MonitorAutoLock" signature in a few other crash reports but couldn't pinpoint the root cause.
Potentially happens when multiple videos are playing at the same time on the page (the reuters page autoplays like 4 of them ... :crazy:)

Crash point:
````
MediaTaskQueue::Dispatch(TemporaryRef<nsIRunnable> aRunnable)
{
0FF34EE0  push        esi  
0FF34EE1  mov         esi,ecx  
0FF34EE3  push        edi  
=>>  MonitorAutoLock mon(mQueueMonitor);
0FF34EE4  push        dword ptr [esi+0Ch]  
0FF34EE7  call        dword ptr ds:[1065C7DCh]  
  return DispatchLocked(aRunnable, AbortIfFlushing);
0FF34EED  mov         eax,dword ptr [esp+10h]  
  MonitorAutoLock mon(mQueueMonitor);
0FF34EF1  add         esp,4  
````
Source:
````
nsresult
MediaTaskQueue::Dispatch(TemporaryRef<nsIRunnable> aRunnable)
{
  MonitorAutoLock mon(mQueueMonitor);
  return DispatchLocked(aRunnable, AbortIfFlushing);
}
````
Crash at `MonitorAutoLock mon(mQueueMonitor);`
So, potential UAF on mQueueMonitor? It's peculiar that it crashes on the statement to hold the pointer.

### PR DESCRIPTION
**Pull request by trav90**
Hopefully fixes #896. Seems to prevent crashing on the reported Reuters sites during my limited testing so far.

### CODE REVIEW

**Comment by JustOff** [comment]
I also have no crash on [Reuters](http://www.reuters.com/article/us-usa-markets-apple-idUSKBN15S2G3?il=0) with this PR applied.

**Comment by wolfbeast** [comment]
Patch makes sense -- I'll give it some thrashing myself.

**Comment by wolfbeast** [comment]
Verified fixed on Win 7 x64 /PM x86 as well.

**Comment by wolfbeast** [comment]
Also seems to address the occasional hang in Facebook based on limited testing.
Will uplift.

**Comment by wolfbeast** [comment]
Uplifted in [229574e]

**Comment by trav90** [comment]
Verified fixed here on Linux (including Facebook) after much further testing today as well.

**Pull request merged**
