### PR TITLE
Remove 'sdk/context-menu@2'

### PR DESCRIPTION
**Pull request by JustOff**
'sdk/context-menu@2' was introduced by https://bugzilla.mozilla.org/show_bug.cgi?id=1070952 for e10s, never used, undocumented, no dependencies with the rest of code.

### CODE REVIEW

**Comment by wolfbeast** [comment]
OK, so this conflicted.. removing the framescripts was something we weren't going to do, after all, right? Is this PR still applicable or not?

**Comment by JustOff** [comment]
Yes, it's applicable, I've updated PR.

**Comment by JustOff** [comment]
Now all resolved properly (sorry about two steps).

**Comment by wolfbeast** [comment]
Ah, okay.

**Pull request merged**
